Handle NoneType in VersionRange.from_string
nexB/univers pull request #115
Opened 2023-08-29 21:09 UTC by keshav-space

- fixes https://github.com/nexB/univers/issues/113

2023-08-30 08:05 UTC, TG1999 requested changes

2023-08-30 08:21 UTC, keshav-space commented on src/univers/version_range.py
> +            raise ValueError("A vers string argument is required.")
Done :)

2023-08-30 08:22 UTC, TG1999 commented
@keshav-space thanks, I think we should update the CI with the skeleton, some of these configurations are not supported any more.

2023-08-31 16:16 UTC, TG1999 approved these changes
LGTM! thanks++

2023-08-31 16:17 UTC, merged