add alpine support in univers
nexB/univers pull request #39
Opened 2022-02-15 14:24 UTC by TG1999

Signed-off-by: Tushar Goel <tushar.goel.dav@gmail.com>

closes issue #37

2022-02-15 18:00 UTC, pombredanne requested changes
Thanks! I have a few nitpickings for your review!

2022-02-16 10:19 UTC, TG1999 commented on tests/data/alpine_test.txt.ABOUT
> +license_expression: gpl-2.0
We already have one `gpl-2.0.LICENSE` file in the data directory

2022-02-16 10:28 UTC, TG1999 commented on src/univers/debian.py
> -                    "Performing lexical comparison between characters %r and %r ..", c1, c2
I ran just black, fixing it now

2022-02-16 10:28 UTC, TG1999 commented on tests/test_maven_version.py
> -            assert v._parsed == expected, "Version(%s) == %s, want %s" % (test, v._parsed, expected)
I ran just black, fixing it now

2022-02-16 13:40 UTC, TG1999 commented on src/univers/version_range.py
> +    scheme = "alpinelinux"
use scheme 'alpine'

2022-02-16 13:41 UTC, TG1999 commented on src/univers/version_range.py
> +    scheme = "alpinelinux"
```suggestion
    scheme = "alpine"
```

2022-02-16 13:42 UTC, TG1999 commented on src/univers/versions.py
> +def valid_alpine_version(s):
```suggestion
def is_valid_alpine_version(s):
```

2022-02-16 21:24 UTC, pombredanne approved these changes
macOS is dead @Azure and we need to merge the latest skeleton, so ignore the failures.
This is looking great!
Thanks... merging!

2022-02-16 21:24 UTC, merged