Add inverse function to VersionRange #91
nexB/univers pull request #92
Opened 2022-11-09 17:13 UTC by TG1999

Signed-off-by: Tushar Goel <tushar.goel.dav@gmail.com>

2022-11-09 17:15 UTC, TG1999 commented
@pombredanne I made inversion of each comparator here:
```
INVERTED_COMPARATORS = {
    ">=": "<",
    "<=": ">",
    "!=": "=",
    "<": ">=",
    ">": "<=",
    "=": "!=",
    "*": "^",
    "^": "*",
}
```
would like to get your opinion on this

2022-11-11 17:25 UTC, pombredanne requested changes
Thanks... see some comments for your review

2022-11-11 17:25 UTC, pombredanne commented on src/univers/version_constraint.py
> +    Comparison operator for the star "^" constraint comparator. Since it does not matches
Is star a caret "^"?

2022-11-11 17:25 UTC, pombredanne commented on src/univers/version_constraint.py
> +    "^": operator_null,
Do we really want to introduce this new syntax? Please explain the rationale and need in detail in a comment or in PR comment.

2022-11-11 17:25 UTC, pombredanne commented on src/univers/version_constraint.py
> +        if not version and comparator not in ["*", "^"]:
Nothing should be just nothing and not caret ^ IMHO

2022-11-11 17:25 UTC, pombredanne commented on src/univers/version_range.py
> +    def inverse(self):
```suggestion
    def invert(self):
```

2022-11-16 14:09 UTC, pombredanne requested changes
Thanks!
see my review inline for your consideration.
IMHO the inversion should be first a method on a constraint and then second a range method that use the constraints method.
We would need a few unit tests rather than only data driven tests, and we could get fewer tests by removing duplicated tests.

2022-11-16 14:09 UTC, pombredanne commented on tests/data/inverse-data.json
> +[
Are you sure you need all these cases? It looks like a many of them are testing identical things? Let's try to keep only one tests of each kind.

2022-11-16 14:09 UTC, pombredanne commented on src/univers/version_range.py
> +            if constraint.comparator in INVERTED_COMPARATORS:
By construction it is impossible to get an unknown comparator so late n the process, so you can safely do this instead and do not need to ever raise anything
```suggestion
            inverted_comparator = INVERTED_COMPARATORS[constraint.comparator]
```

2022-11-16 14:09 UTC, pombredanne commented on src/univers/version_range.py
> +                raise NotImplementedError(
```suggestion
```

2022-11-16 14:09 UTC, pombredanne commented on src/univers/version_range.py
> +            inverted_constraint = VersionConstraint(
Should this rather be an invert()  method on VersionConstraint?

2022-11-21 12:42 UTC, pombredanne requested changes
Thanks. Here are a few extra nit pickings for your consideration.

2022-11-21 12:42 UTC, pombredanne commented on src/univers/version_constraint.py
> +        INVERTED_COMPARATORS = {
Please add a docstring

2022-11-21 12:42 UTC, pombredanne commented on tests/test_version_range.py
> +def test_inverse():
You need tests for the lower level constraint.invert e.g.,  for https://github.com/nexB/univers/pull/92/files#diff-c77d34029ce1991650937489359eef45029f37be4f1f27c21f56e50e64209d9aR138 too

2022-11-21 13:06 UTC, TG1999 commented on src/univers/version_constraint.py
> +        INVERTED_COMPARATORS = {
Done!

2022-11-21 15:33 UTC, pombredanne approved these changes
LGTM!
:+1:

2022-11-23 11:16 UTC, merged